name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: test
        run: |
          corepack enable
          pnpm install --frozen-lockfile
          pnpm run format:check
      - name: summary
        run: |
          echo >> $GITHUB_STEP_SUMMARY '# Summary'
          echo >> $GITHUB_STEP_SUMMARY ''
          echo >> $GITHUB_STEP_SUMMARY Repository is correctly formatted! :tada:
